steps:

    - name: gcr.io/cloud-builders/docker
      id: app
      args:
          - build
          - -f
          - docker/Dockerfile.app
          - -t
          - europe-west8-docker.pkg.dev/uninsubria-data-science/larionow-dataset/app:latest
          - .

    - name: gcr.io/cloud-builders/docker
      id: collector
      args:
          - build
          - -f
          - docker/Dockerfile.etl
          - -t
          - europe-west8-docker.pkg.dev/uninsubria-data-science/larionow-dataset/collector:latest
          - .

    - name: gcr.io/cloud-builders/docker
      id: retraining
      args:
          - build
          - -f
          - docker/Dockerfile.train
          - -t
          - europe-west8-docker.pkg.dev/uninsubria-data-science/larionow-dataset/retraining:latest
          - .

images:
    - europe-west8-docker.pkg.dev/uninsubria-data-science/larionow-dataset/app:latest
    - europe-west8-docker.pkg.dev/uninsubria-data-science/larionow-dataset/collector:latest
    - europe-west8-docker.pkg.dev/uninsubria-data-science/larionow-dataset/retraining:latest
